# Generated by Django 3.2.7 on 2021-09-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210919_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Finalización'),
        ),
    ]
