# Generated by Django 3.2.7 on 2021-09-19 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_alter_task_finish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_finalized',
            field=models.BooleanField(default=False, null=True, verbose_name='Está Finalizada?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
