# Generated by Django 3.2.7 on 2021-09-19 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_types', '0001_initial'),
        ('cities', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='city',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cities.city', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='document_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='document_types.documenttype', verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities.city', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='document_types.documenttype', verbose_name='Tipo de Documento'),
        ),
    ]
